### ISSUE TITLE
Update to elm 0.19

### ISSUE THREAD

**Issue by andys8** [haskell-servant/example-servant-elm#6]
Elm 0.19 is released. We have to wait for https://github.com/mattjbray/servant-elm/issues/44 to arrive. But otherwise this repository can be updated.

All Elm dependencies but `elm-html-test` were updated. It looks like `elm-html-test` is listed, but not used in the codebase.

![screenshot_20181010-233945](https://user-images.githubusercontent.com/13085980/46767709-0ef0b300-cce6-11e8-866a-b136f70b01ce.png)
https://kraklin.github.io/elm-readiness/

**Comment by k-bx** [comment]
See work done in https://github.com/haskell-servant/servant-elm/pull/49

**Comment by FranklinChen** [comment]
Eventually I'll get around to updating my incomplete pull request https://github.com/haskell-servant/example-servant-elm/pull/7 to use `elm-bridge`, unless someone wants to take over and start with that Elm 0.19 fork to do that.

**Comment by k-bx** [comment]
Just FYI, it's not a fork anymore, but a released version of servant-elm package (currently 0.6.0.2) http://hackage.haskell.org/package/servant-elm

**Comment by FranklinChen** [comment]
I was referring to my fork and branch of this project https://github.com/FranklinChen/example-servant-elm/tree/elm-0.19

I have already begun using servant-elm 0.6.0.2 in this branch.
